### ISSUE TITLE
Parametrize Tests for Accessibility Rules

### ISSUE THREAD

**Issue by kimberlythegeek** [kimberlythegeek/axe-selenium-python#1]
Use pytest parametrize for tests in test_accessibility_rules.py
 
https://docs.pytest.org/en/latest/parametrize.html

**Comment by kimberlythegeek** [comment]
Experimented with parametrize in [issue_1 branch](https://github.com/kimberlythegeek/axe-selenium-python/blob/issue_1/axe_selenium_python/tests/test_parametrize_rules.py)

Unsure if this is the way to go. 

Documentation on https://docs.pytest.org/en/latest/parametrize.html shows two methods. One requires the values to be hard-coded into the decorator. 

(Tried using pytestconfig to do this dynamically, but `parametrize` is called before the function, and cannot access the pytestconfig object at this point as far as I know).

The second option allows for the dynamic generation of tests, but the example given uses command line arguments, rather than data acquired during the tests.

@m8ttyB

**Comment by kimberlythegeek** [comment]
Even if we went with this hard-coded approach, I don't think the traceback for this approach is desirable for our purposes.

Here is an example for just one failed rule: https://gist.github.com/kimberlythegeek/9c53e1c3a0b23f2589094c97eaf961b0

A blob like this returns for every rule that fails.

**Comment by m8ttyB** [comment]
Let's discuss this when we meet. My thought was that the array of rules could be moved into a class level variable. That variable could then be passed to the `parametrize` function. The open question is, how do we override the `rules` list in a reasonable way.

Here's an [example from the go-bouncer project](https://github.com/mozilla-services/go-bouncer/blob/master/tests/e2e/tests/test_redirects.py#L84-L106).
```
class Test:
  _rules = [
     'accesskeys',
     'area-alt',
     'aria-allowed-attr',
     'aria-hidden-body',
     'aria-required-attr',
     'aria-required-children']

 @pytest.mark.parametrize('rule', _rules)
  def test_rule(self, rule):
    assert rule not in pytestconfig.violations, pytestconfig.violations[rule]['help']
```
