### ISSUE TITLE
Rename package to suit naming conventions

### ISSUE THREAD

**Issue by kimberlythegeek** [kimberlythegeek/axe-selenium-python#28]
recommended by tarek: 'axeselenium'

**Comment by kimberlythegeek** [comment]
will require some extra steps since this package has already been published to pypi

**Comment by m8ttyB** [comment]
Should this be a part of the milestone for 1.0?

**Comment by kimberlythegeek** [comment]
Will keep the name `axe-selenium-python` for consistency, as this package is based off of Deque's axe-selenium-java.
